use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() -> io::Result<()> {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let asset_root = manifest_dir.join("static");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    println!("cargo:rerun-if-changed={}", asset_root.display());

    let mut files = Vec::new();
    collect_files(&asset_root, &asset_root, &mut files)?;
    files.sort();

    let mut generated = String::from(
        "// @generated by crates/ironclaw_gateway_reborn/build.rs\n\
         pub const INDEX_HTML: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/static/index.html\"));\n\n\
         pub fn asset_bytes(path: &str) -> Option<&'static [u8]> {\n\
         \x20\x20\x20\x20match path {\n",
    );

    for path in &files {
        let escaped_path = rust_string(path);
        generated.push_str(&format!(
            "        \"{escaped_path}\" => Some(include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/static/{escaped_path}\")).as_slice()),\n"
        ));
    }

    generated.push_str(
        "        _ => None,\n\
         \x20\x20\x20\x20}\n\
         }\n",
    );

    fs::write(out_dir.join("reborn_assets.rs"), generated)
}

fn collect_files(root: &Path, dir: &Path, files: &mut Vec<String>) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", dir.display());
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            collect_files(root, &path, files)?;
        } else if file_type.is_file() {
            println!("cargo:rerun-if-changed={}", path.display());
            let relative = path.strip_prefix(root).expect("path under root");
            files.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
    Ok(())
}

fn rust_string(value: &str) -> String {
    value.escape_default().collect()
}
