//! Static Reborn extension capability surface used by binary-E2E tests.

pub const EXTENSION_SEARCH_CAPABILITY_ID: &str = "builtin.extension_search";
pub const EXTENSION_INSTALL_CAPABILITY_ID: &str = "builtin.extension_install";
pub const EXTENSION_ACTIVATE_CAPABILITY_ID: &str = "builtin.extension_activate";
pub const EXTENSION_REMOVE_CAPABILITY_ID: &str = "builtin.extension_remove";

pub const EXTENSION_LIFECYCLE_CAPABILITY_IDS: &[&str] = &[
    EXTENSION_SEARCH_CAPABILITY_ID,
    EXTENSION_INSTALL_CAPABILITY_ID,
    EXTENSION_ACTIVATE_CAPABILITY_ID,
    EXTENSION_REMOVE_CAPABILITY_ID,
];

pub const BUNDLED_EXTENSION_IDS: &[&str] = &[
    "github",
    "web-access",
    "gmail",
    "google-calendar",
    "google-docs",
    "google-sheets",
    "google-drive",
    "google-slides",
    "nearai",
    "notion",
];

pub const BUNDLED_EXTENSION_CAPABILITY_IDS: &[&str] = &[
    "github.search_issues",
    "github.get_issue",
    "github.comment_issue",
    "web-access.search",
    "web-access.get_content",
    "gmail.list_messages",
    "gmail.get_message",
    "gmail.send_message",
    "gmail.create_draft",
    "gmail.reply_to_message",
    "gmail.trash_message",
    "google-calendar.list_calendars",
    "google-calendar.list_events",
    "google-calendar.get_event",
    "google-calendar.find_free_slots",
    "google-calendar.create_event",
    "google-calendar.update_event",
    "google-calendar.delete_event",
    "google-calendar.add_attendees",
    "google-calendar.set_reminder",
    "google-docs.create_document",
    "google-docs.get_document",
    "google-docs.read_content",
    "google-docs.insert_text",
    "google-docs.delete_content",
    "google-docs.replace_text",
    "google-docs.format_text",
    "google-docs.format_paragraph",
    "google-docs.insert_table",
    "google-docs.create_list",
    "google-docs.batch_update",
    "google-sheets.create_spreadsheet",
    "google-sheets.get_spreadsheet",
    "google-sheets.read_values",
    "google-sheets.batch_read_values",
    "google-sheets.write_values",
    "google-sheets.append_values",
    "google-sheets.clear_values",
    "google-sheets.add_sheet",
    "google-sheets.delete_sheet",
    "google-sheets.rename_sheet",
    "google-sheets.format_cells",
    "google-drive.list_files",
    "google-drive.get_file",
    "google-drive.download_file",
    "google-drive.upload_file",
    "google-drive.update_file",
    "google-drive.create_folder",
    "google-drive.delete_file",
    "google-drive.trash_file",
    "google-drive.share_file",
    "google-drive.list_permissions",
    "google-drive.remove_permission",
    "google-drive.list_shared_drives",
    "google-slides.create_presentation",
    "google-slides.get_presentation",
    "google-slides.get_thumbnail",
    "google-slides.create_slide",
    "google-slides.delete_object",
    "google-slides.insert_text",
    "google-slides.delete_text",
    "google-slides.replace_all_text",
    "google-slides.create_shape",
    "google-slides.insert_image",
    "google-slides.format_text",
    "google-slides.format_paragraph",
    "google-slides.replace_shapes_with_image",
    "google-slides.batch_update",
    "nearai.web_search",
    "notion.notion-search",
    "notion.notion-fetch",
    "notion.notion-create-pages",
    "notion.notion-update-page",
    "notion.notion-move-pages",
    "notion.notion-duplicate-page",
    "notion.notion-create-database",
    "notion.notion-update-data-source",
    "notion.notion-create-view",
    "notion.notion-update-view",
    "notion.notion-query-data-sources",
    "notion.notion-query-database-view",
    "notion.notion-create-comment",
    "notion.notion-get-comments",
    "notion.notion-get-teams",
    "notion.notion-get-users",
    "notion.notion-get-user",
    "notion.notion-get-self",
];
