//! Durable [`LibSqlPredicateStateBackend`] verified against the shared
//! `PredicateStateBackend` contract suite from `ironclaw_hooks`
//! (durable-backend PR 3/4), plus libSQL-specific adversarial tests
//! (concurrent writers, cross-host replay, LRU + per-key cap under pressure).
//!
//! # Why `harness = false` + a hand-rolled serial runner
//!
//! This test binary opts out of the default libtest harness (see the
//! `[[test]]` entry in `Cargo.toml`). Several cases fill a single key all the
//! way to `MAX_SAMPLES_PER_KEY` (4 096) — each step is a fresh
//! connect / `BEGIN IMMEDIATE` / `COMMIT` cycle, because the backend opens a
//! connection per operation (no pool). Running several of those 4 096-step
//! fill loops *concurrently* against the replication-enabled libSQL build
//! intermittently trips `SQLITE_MISUSE` ("bad parameter or other API misuse").
//! Single-threaded, every case passes deterministically.
//!
//! The default harness offers no in-crate knob to cap parallelism for one test
//! binary, and the fail-closed contract case is generated by a cross-crate
//! macro we cannot gate. So we own the runner: cases run **serially** by
//! default (one heavy fill at a time), and the cases that intentionally
//! exercise concurrency get their own multi-thread Tokio runtime. The
//! `contract-tests` feature on the `ironclaw_hooks` dev-dependency exposes the
//! `predicate_state::contract` functions we call directly here instead of
//! through the `predicate_backend_contract_test!` macro.

use std::future::Future;
use std::panic::{self, AssertUnwindSafe};
use std::sync::Arc;
use std::time::Duration;

use chrono::{DateTime, Utc};
use ironclaw_hooks::identity::{ExtensionId, HookId, HookLocalId, HookVersion};
use ironclaw_hooks::predicate_state::{
    InvocationKey, MAX_KEYS_PER_TENANT, MAX_SAMPLES_PER_KEY, PredicateBackendError,
    PredicateEventId, PredicateStateBackend, ValueKey, contract,
};
use ironclaw_hooks_libsql::LibSqlPredicateStateBackend;
use ironclaw_host_api::TenantId;
use rust_decimal::Decimal;
use tempfile::TempDir;

// ---------------------------------------------------------------------------
// Serial runner
// ---------------------------------------------------------------------------

/// Which Tokio runtime flavor a case needs.
enum Rt {
    /// Single-threaded current-thread runtime (the default; serialises heavy
    /// fill loops so at most one runs at a time across the binary).
    Current,
    /// Multi-thread runtime for cases that intentionally exercise concurrency.
    Multi { workers: usize },
}

/// Run one case on a freshly-built runtime, catching panics so a failure in one
/// case still lets the rest run and the final exit code reflects all failures.
fn run<F, Fut>(name: &str, rt: Rt, f: F) -> bool
where
    F: FnOnce() -> Fut,
    Fut: Future<Output = ()>,
{
    eprint!("test {name} ... ");
    let result = panic::catch_unwind(AssertUnwindSafe(|| match rt {
        Rt::Current => tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("build current-thread runtime")
            .block_on(f()),
        Rt::Multi { workers } => tokio::runtime::Builder::new_multi_thread()
            .worker_threads(workers)
            .enable_all()
            .build()
            .expect("build multi-thread runtime")
            .block_on(f()),
    }));
    match result {
        Ok(()) => {
            eprintln!("ok");
            true
        }
        Err(_) => {
            eprintln!("FAILED");
            false
        }
    }
}

fn main() {
    let mut ok = true;

    // Shared PredicateStateBackend contract suite (mirrors the cases the
    // `predicate_backend_contract_test!` macro would generate). All run on a
    // single-threaded runtime; the overflow case is a heavy 4 096 fill.
    ok &= run(
        "contract::invocation_counts_within_window",
        Rt::Current,
        || contract::invocation_counts_within_window(contract_factory),
    );
    ok &= run(
        "contract::invocation_trims_outside_window",
        Rt::Current,
        || contract::invocation_trims_outside_window(contract_factory),
    );
    ok &= run("contract::value_sums_within_window", Rt::Current, || {
        contract::value_sums_within_window(contract_factory)
    });
    ok &= run("contract::tenant_isolation", Rt::Current, || {
        contract::tenant_isolation(contract_factory)
    });
    ok &= run(
        "contract::duplicate_event_id_is_noop_for_invocations",
        Rt::Current,
        || contract::duplicate_event_id_is_noop_for_invocations(contract_factory),
    );
    ok &= run(
        "contract::duplicate_event_id_is_noop_for_values",
        Rt::Current,
        || contract::duplicate_event_id_is_noop_for_values(contract_factory),
    );
    ok &= run(
        "contract::invocation_retains_entry_at_exact_window_cutoff",
        Rt::Current,
        || contract::invocation_retains_entry_at_exact_window_cutoff(contract_factory),
    );
    ok &= run(
        "contract::event_id_dedup_isolated_across_maps",
        Rt::Current,
        || contract::event_id_dedup_isolated_across_maps(contract_factory),
    );
    ok &= run(
        "contract::record_invocation_overflow_is_fail_closed",
        Rt::Current,
        || contract::record_invocation_overflow_is_fail_closed(contract_factory),
    );

    // libSQL-specific adversarial cases.
    ok &= run(
        "two_hosts_concurrent_writes_no_desync",
        Rt::Multi { workers: 4 },
        two_hosts_concurrent_writes_no_desync,
    );
    ok &= run(
        "cross_host_replay_is_deduped",
        Rt::Current,
        cross_host_replay_is_deduped,
    );
    ok &= run(
        "cross_host_replay_is_deduped_for_values",
        Rt::Current,
        cross_host_replay_is_deduped_for_values,
    );
    ok &= run(
        "per_key_sample_cap_fails_closed_under_pressure",
        Rt::Current,
        per_key_sample_cap_fails_closed_under_pressure,
    );
    ok &= run(
        "value_sum_cap_fails_closed",
        Rt::Current,
        value_sum_cap_fails_closed,
    );
    ok &= run(
        "per_tenant_quota_isolates_under_concurrent_pressure",
        Rt::Multi { workers: 4 },
        per_tenant_quota_isolates_under_concurrent_pressure,
    );
    ok &= run(
        "state_survives_restart",
        Rt::Current,
        state_survives_restart,
    );

    if !ok {
        eprintln!("\nsome predicate_state_contract cases FAILED");
        std::process::exit(1);
    }
    eprintln!("\nall predicate_state_contract cases ok");
}

// ---------------------------------------------------------------------------
// Backend construction helpers
// ---------------------------------------------------------------------------

/// Build a fresh, migrated libSQL-backed backend over a private temp-file
/// database. Returns the backend plus the `TempDir` guard (kept alive by the
/// caller for the duration of the test).
async fn fresh_backend() -> (LibSqlPredicateStateBackend, TempDir) {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("predicate_state.db");
    let db = Arc::new(
        libsql::Builder::new_local(path.to_string_lossy().to_string())
            .build()
            .await
            .expect("build libsql db"),
    );
    let backend = LibSqlPredicateStateBackend::new(db);
    backend.run_migrations().await.expect("migrate");
    (backend, dir)
}

/// Synchronous factory for the contract functions (which take `Fn() -> B`).
/// Builds the async-constructed backend on a dedicated current-thread runtime
/// on a fresh OS thread — avoids "cannot start a runtime from within a runtime"
/// since the caller is already inside a runtime via [`run`]. Leaks the
/// `TempDir` into the process so the db file outlives the contract body; the
/// test process is short-lived so a handful of leaked temp dirs is fine.
fn contract_factory() -> LibSqlPredicateStateBackend {
    std::thread::scope(|s| {
        s.spawn(|| {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("build current-thread runtime");
            rt.block_on(async {
                let (backend, dir) = fresh_backend().await;
                Box::leak(Box::new(dir));
                backend
            })
        })
        .join()
        .expect("setup thread joined")
    })
}

// ---------------------------------------------------------------------------
// Adversarial test fixtures
// ---------------------------------------------------------------------------

fn hook_id() -> HookId {
    HookId::derive(
        &ExtensionId::new("ext").expect("ext id"),
        "1.0",
        &HookLocalId::new("h").expect("hook local id"),
        HookVersion::ONE,
    )
}

fn tenant(name: &str) -> TenantId {
    TenantId::new(name).expect("tenant id")
}

fn ev(s: &str) -> PredicateEventId {
    PredicateEventId::new(s).expect("event id")
}

fn base() -> DateTime<Utc> {
    DateTime::from_timestamp(1_700_000_000, 0).expect("fixed timestamp")
}

fn at_secs(secs: i64) -> DateTime<Utc> {
    base() + chrono::Duration::seconds(secs)
}

fn at_millis(ms: i64) -> DateTime<Utc> {
    base() + chrono::Duration::milliseconds(ms)
}

fn inv_key(tenant_name: &str, capability: &str) -> InvocationKey {
    InvocationKey {
        hook_id: hook_id(),
        tenant_id: tenant(tenant_name),
        capability: capability.to_string(),
    }
}

fn val_key(tenant_name: &str, capability: &str, field: &str) -> ValueKey {
    ValueKey {
        hook_id: hook_id(),
        tenant_id: tenant(tenant_name),
        capability: capability.to_string(),
        field: field.to_string(),
    }
}

/// Build a backend over a shared temp-file db (the `Database` handle is
/// returned so a second backend can open the SAME database, simulating a
/// second host).
async fn shared_db_backend() -> (Arc<libsql::Database>, TempDir) {
    let dir = tempfile::tempdir().expect("tempdir");
    let path = dir.path().join("shared.db");
    let db = Arc::new(
        libsql::Builder::new_local(path.to_string_lossy().to_string())
            .build()
            .await
            .expect("build libsql db"),
    );
    let backend = LibSqlPredicateStateBackend::new(db.clone());
    backend.run_migrations().await.expect("migrate");
    (db, dir)
}

// ---------------------------------------------------------------------------
// Adversarial cases
// ---------------------------------------------------------------------------

/// Two simulated hosts (two `LibSqlPredicateStateBackend` instances over the
/// same db file) hammer the same invocation key concurrently with DISTINCT
/// event ids. `BEGIN IMMEDIATE` must serialise the read-modify-write so every
/// write is counted exactly once — the final count equals the number of
/// distinct ids (no lost-update desync).
async fn two_hosts_concurrent_writes_no_desync() {
    let (db, _dir) = shared_db_backend().await;
    let host_a = Arc::new(LibSqlPredicateStateBackend::new(db.clone()));
    let host_b = Arc::new(LibSqlPredicateStateBackend::new(db.clone()));
    let key = inv_key("alpha", "cap.concurrent");
    let now = at_secs(0);
    let window = Duration::from_secs(60);

    const N: usize = 24;
    let mut handles = Vec::with_capacity(N);
    for i in 0..N {
        let backend = if i % 2 == 0 {
            Arc::clone(&host_a)
        } else {
            Arc::clone(&host_b)
        };
        let key = key.clone();
        handles.push(tokio::spawn(async move {
            backend
                .record_invocation(&key, &ev(&format!("event-{i}")), now, window)
                .await
                .expect("record ok")
        }));
    }
    for h in handles {
        h.await.expect("task joined");
    }
    // Re-read via a duplicate id (no-op insert) on a THIRD instance.
    let observer = LibSqlPredicateStateBackend::new(db.clone());
    let final_count = observer
        .record_invocation(&key, &ev("event-0"), now, window)
        .await
        .expect("read ok");
    assert_eq!(
        final_count as usize, N,
        "two hosts writing distinct ids concurrently must each be counted exactly once"
    );
}

/// Cross-host replay dedup: host A records an event, host B replays the SAME
/// event id against the SAME key. The durable PRIMARY KEY must dedup across
/// hosts (the property the in-memory backend explicitly cannot provide).
async fn cross_host_replay_is_deduped() {
    let (db, _dir) = shared_db_backend().await;
    let host_a = LibSqlPredicateStateBackend::new(db.clone());
    let host_b = LibSqlPredicateStateBackend::new(db.clone());
    let key = inv_key("alpha", "cap.replay");
    let window = Duration::from_secs(60);

    let c1 = host_a
        .record_invocation(&key, &ev("shared-evt"), at_secs(0), window)
        .await
        .expect("ok");
    assert_eq!(c1, 1);

    // Host B replays the same event id — must be a no-op against the count.
    let c2 = host_b
        .record_invocation(&key, &ev("shared-evt"), at_secs(1), window)
        .await
        .expect("ok");
    assert_eq!(
        c2, 1,
        "cross-host replay of a recorded event id must not increment"
    );

    // A distinct id on host B does advance.
    let c3 = host_b
        .record_invocation(&key, &ev("fresh-evt"), at_secs(2), window)
        .await
        .expect("ok");
    assert_eq!(c3, 2);
}

/// Cross-host replay dedup for the value path.
async fn cross_host_replay_is_deduped_for_values() {
    let (db, _dir) = shared_db_backend().await;
    let host_a = LibSqlPredicateStateBackend::new(db.clone());
    let host_b = LibSqlPredicateStateBackend::new(db.clone());
    let key = val_key("alpha", "cap.spend", "amount");
    let window = Duration::from_secs(60);

    let s1 = host_a
        .record_value(
            &key,
            &ev("shared-evt"),
            at_secs(0),
            Decimal::from(50),
            window,
        )
        .await
        .expect("ok");
    assert_eq!(s1, Decimal::from(50));

    let s2 = host_b
        .record_value(
            &key,
            &ev("shared-evt"),
            at_secs(1),
            Decimal::from(50),
            window,
        )
        .await
        .expect("ok");
    assert_eq!(
        s2,
        Decimal::from(50),
        "cross-host replay must not double-count the value sum"
    );
}

/// Per-key sample cap is FAIL CLOSED under sustained pressure (#3929):
/// inserting exactly `MAX_SAMPLES_PER_KEY` distinct in-window events succeeds,
/// then the next distinct in-window id returns
/// [`PredicateBackendError::WindowOverflow`] rather than silently dropping the
/// oldest. Replaying an already-recorded in-window id at the cap dedups to a
/// no-op (returns the unchanged count), so replay refusal survives the cap.
async fn per_key_sample_cap_fails_closed_under_pressure() {
    let (backend, _dir) = fresh_backend().await;
    let key = inv_key("alpha", "cap.hot");
    let window = Duration::from_secs(3600);

    // Fill exactly to the cap with distinct in-window ids — all succeed.
    for i in 0..MAX_SAMPLES_PER_KEY {
        let count = backend
            .record_invocation(&key, &ev(&format!("evt-{i}")), at_millis(i as i64), window)
            .await
            .expect("inserts up to the cap succeed");
        assert_eq!(count as usize, i + 1);
    }

    // The next distinct in-window id must fail closed.
    let result = backend
        .record_invocation(
            &key,
            &ev("evt-overflow"),
            at_millis(MAX_SAMPLES_PER_KEY as i64),
            window,
        )
        .await;
    assert!(
        matches!(result, Err(PredicateBackendError::WindowOverflow { .. })),
        "hitting the per-key cap must fail closed, got {result:?}"
    );

    // A replay of an in-window id at the cap dedups to a no-op.
    let replay = backend
        .record_invocation(
            &key,
            &ev("evt-0"),
            at_millis(MAX_SAMPLES_PER_KEY as i64 + 1),
            window,
        )
        .await
        .expect("replay of an in-window id must dedup, not overflow");
    assert_eq!(
        replay as usize, MAX_SAMPLES_PER_KEY,
        "replay at the cap is a no-op against the count"
    );
}

/// Value-path per-key cap is also FAIL CLOSED (#3929): filling to the cap with
/// distinct in-window value events succeeds (the sum equals `cap * value`
/// exactly, recomputed from surviving rows), then a new distinct id overflows
/// rather than dropping the oldest sample (which would silently undercount).
async fn value_sum_cap_fails_closed() {
    let (backend, _dir) = fresh_backend().await;
    let key = val_key("alpha", "cap.spend", "amount");
    let window = Duration::from_secs(3600);
    let value = Decimal::from(3);

    let mut last = Decimal::ZERO;
    for i in 0..MAX_SAMPLES_PER_KEY {
        last = backend
            .record_value(
                &key,
                &ev(&format!("v-{i}")),
                at_millis(i as i64),
                value,
                window,
            )
            .await
            .expect("inserts up to the cap succeed");
    }
    assert_eq!(
        last,
        Decimal::from(MAX_SAMPLES_PER_KEY as u64) * value,
        "at-cap sum must equal cap * value (recomputed from surviving rows)"
    );

    // The next distinct in-window id must fail closed.
    let result = backend
        .record_value(
            &key,
            &ev("v-overflow"),
            at_millis(MAX_SAMPLES_PER_KEY as i64),
            value,
            window,
        )
        .await;
    assert!(
        matches!(result, Err(PredicateBackendError::WindowOverflow { .. })),
        "hitting the per-key value cap must fail closed, got {result:?}"
    );
}

/// Per-tenant LRU quota under concurrent pressure: a single noisy tenant
/// inserting more than `MAX_KEYS_PER_TENANT` distinct scopes must be held at
/// its quota (its own oldest scopes evicted) and must NOT evict a quiet
/// tenant's scope. Drives the public API concurrently to exercise the
/// serialised eviction path.
async fn per_tenant_quota_isolates_under_concurrent_pressure() {
    let (db, _dir) = shared_db_backend().await;
    let backend = Arc::new(LibSqlPredicateStateBackend::new(db.clone()));
    let window = Duration::from_secs(60);

    // Quiet tenant β records one scope first.
    let beta_key = inv_key("beta", "beta.cap");
    backend
        .record_invocation(&beta_key, &ev("beta-evt"), at_secs(0), window)
        .await
        .expect("ok");

    // Noisy tenant α floods past its quota. libSQL opens a fresh connection
    // per operation against a single file; an unbounded fan-out of thousands
    // of simultaneous opens exhausts OS file handles (SQLite CANTOPEN), so we
    // bound concurrency with a semaphore. The contention that matters — many
    // writers serialising on the single `BEGIN IMMEDIATE` write lock and the
    // eviction path racing — is fully exercised with a bounded pool.
    let flood = MAX_KEYS_PER_TENANT + 16;
    let sem = Arc::new(tokio::sync::Semaphore::new(16));
    let mut handles = Vec::with_capacity(flood);
    for i in 0..flood {
        let backend = Arc::clone(&backend);
        let sem = Arc::clone(&sem);
        handles.push(tokio::spawn(async move {
            let _permit = sem.acquire_owned().await.expect("permit");
            let key = inv_key("alpha", &format!("alpha.cap.{i}"));
            backend
                .record_invocation(
                    &key,
                    &ev(&format!("alpha-e{i}")),
                    at_millis(i as i64 + 1),
                    window,
                )
                .await
                .expect("ok");
        }));
    }
    for h in handles {
        h.await.expect("joined");
    }

    // β's scope must survive (α can only evict its own scopes).
    let beta_count = backend
        .record_invocation(&beta_key, &ev("beta-evt"), at_secs(0), window)
        .await
        .expect("ok");
    assert_eq!(
        beta_count, 1,
        "quiet tenant β's scope must survive noisy tenant α's flood (replay no-op confirms it persists)"
    );

    // α must be held at its per-tenant quota.
    let alpha_scopes = count_distinct_scopes(&db, "hooks_predicate_invocations", "alpha").await;
    assert!(
        alpha_scopes <= MAX_KEYS_PER_TENANT,
        "noisy tenant α must be capped at its per-tenant quota; got {alpha_scopes}"
    );
}

async fn count_distinct_scopes(db: &Arc<libsql::Database>, table: &str, tenant: &str) -> usize {
    let conn = db.connect().expect("connect");
    let mut rows = conn
        .query(
            &format!("SELECT count(DISTINCT scope_hash) FROM {table} WHERE tenant_id = ?1"),
            libsql::params![tenant],
        )
        .await
        .expect("query");
    let row = rows.next().await.expect("row").expect("some");
    let v: i64 = row.get(0).expect("i64");
    v.max(0) as usize
}

/// Durable survival across "restart": a backend instance writes, is dropped,
/// and a NEW instance over the SAME db file reads the persisted count.
async fn state_survives_restart() {
    let (db, _dir) = shared_db_backend().await;
    let key = inv_key("alpha", "cap.persist");
    let window = Duration::from_secs(3600);
    {
        let backend = LibSqlPredicateStateBackend::new(db.clone());
        for i in 0..3 {
            backend
                .record_invocation(&key, &ev(&format!("e{i}")), at_secs(i), window)
                .await
                .expect("ok");
        }
    }
    // New instance, same db file — no migration re-run needed.
    let restarted = LibSqlPredicateStateBackend::new(db.clone());
    let count = restarted
        .record_invocation(&key, &ev("e0"), at_secs(3), window)
        .await
        .expect("ok");
    assert_eq!(
        count, 3,
        "persisted count must survive a backend instance restart"
    );
}
