//! Alipay Trade Query WASM Tool for IronClaw.
//!
//! Query Alipay trade and refund status (支付宝).
//! This is a simplified tool that works with a pre-generated gateway token
//! from your backend service, avoiding complex RSA signing in WASM.
//!
//! # Authentication
//!
//! Store your Alipay gateway token:
//! `ironclaw secret set alipay_gateway_token <token>`
//!
//! Get a token from: https://open.alipay.com/

wit_bindgen::generate!({
    world: "sandboxed-tool",
    path: "../../wit/tool.wit",
});

use serde::Deserialize;

const GATEWAY_URL: &str = "https://openapi.alipay.com/gateway.do";
const MAX_RETRIES: u32 = 3;

struct AlipayTool;

impl exports::near::agent::tool::Guest for AlipayTool {
    fn execute(req: exports::near::agent::tool::Request) -> exports::near::agent::tool::Response {
        match execute_inner(&req.params) {
            Ok(result) => exports::near::agent::tool::Response {
                output: Some(result),
                error: None,
            },
            Err(e) => exports::near::agent::tool::Response {
                output: None,
                error: Some(e),
            },
        }
    }

    fn schema() -> String {
        SCHEMA.to_string()
    }

    fn description() -> String {
        "Query Alipay trade and refund status (支付宝交易查询). \
         Check trade payment status and refund status. \
         Uses a simplified gateway token approach — your backend generates the token. \
         Authentication is handled via the 'alipay_gateway_token' secret injected by the host."
            .to_string()
    }
}

#[derive(Debug, Deserialize)]
struct Params {
    action: String,
    trade_no: Option<String>,
    out_trade_no: Option<String>,
    out_request_no: Option<String>,
}

// --- Alipay API response types ---

#[derive(Debug, Deserialize)]
struct AlipayGatewayResponse {
    alipay_trade_query_response: Option<TradeQueryResponse>,
    alipay_trade_fastpay_refund_query_response: Option<RefundQueryResponse>,
    sign: Option<String>,
}

#[derive(Debug, Deserialize)]
struct TradeQueryResponse {
    code: Option<String>,
    msg: Option<String>,
    sub_code: Option<String>,
    sub_msg: Option<String>,
    trade_no: Option<String>,
    out_trade_no: Option<String>,
    trade_status: Option<String>,
    total_amount: Option<String>,
    buyer_logon_id: Option<String>,
    buyer_pay_amount: Option<String>,
    send_pay_date: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RefundQueryResponse {
    code: Option<String>,
    msg: Option<String>,
    sub_code: Option<String>,
    sub_msg: Option<String>,
    trade_no: Option<String>,
    out_trade_no: Option<String>,
    out_request_no: Option<String>,
    refund_status: Option<String>,
    total_amount: Option<String>,
    refund_amount: Option<String>,
    refund_reason: Option<String>,
}

fn execute_inner(params: &str) -> Result<String, String> {
    let params: Params =
        serde_json::from_str(params).map_err(|e| format!("Invalid parameters: {e}"))?;

    if !near::agent::host::secret_exists("alipay_gateway_token") {
        return Err(
            "Alipay gateway token not found in secret store. Set it with: \
             ironclaw secret set alipay_gateway_token <token>. \
             The token must be generated by your backend service. \
             See: https://open.alipay.com/"
                .into(),
        );
    }

    match params.action.as_str() {
        "query_trade" => query_trade(&params),
        "query_refund" => query_refund(&params),
        _ => Err(format!(
            "Unknown action '{}'. Expected: query_trade, query_refund",
            params.action
        )),
    }
}

fn query_trade(params: &Params) -> Result<String, String> {
    let has_trade_no = params.trade_no.as_ref().map_or(false, |s| !s.is_empty());
    let has_out_trade_no = params.out_trade_no.as_ref().map_or(false, |s| !s.is_empty());

    if !has_trade_no && !has_out_trade_no {
        return Err("Either 'trade_no' or 'out_trade_no' is required for query_trade".into());
    }

    let mut biz_content = serde_json::Map::new();
    if let Some(ref trade_no) = params.trade_no {
        if !trade_no.is_empty() {
            biz_content.insert("trade_no".into(), serde_json::json!(trade_no));
        }
    }
    if let Some(ref out_trade_no) = params.out_trade_no {
        if !out_trade_no.is_empty() {
            biz_content.insert("out_trade_no".into(), serde_json::json!(out_trade_no));
        }
    }

    let body = serde_json::json!({
        "method": "alipay.trade.query",
        "charset": "utf-8",
        "format": "JSON",
        "version": "1.0",
        "biz_content": serde_json::to_string(&biz_content)
            .map_err(|e| format!("Failed to serialize biz_content: {e}"))?,
    });

    let resp_body = alipay_request(&body)?;
    let resp: AlipayGatewayResponse =
        serde_json::from_str(&resp_body).map_err(|e| format!("Failed to parse response: {e}"))?;

    let trade = resp.alipay_trade_query_response
        .ok_or("Missing trade query response from Alipay")?;

    if trade.code.as_deref() != Some("10000") {
        let sub_msg = trade.sub_msg.unwrap_or_default();
        let msg = trade.msg.unwrap_or_default();
        return Err(format!("Alipay trade query failed: {} - {}", msg, sub_msg));
    }

    let output = serde_json::json!({
        "action": "query_trade",
        "trade_no": trade.trade_no,
        "out_trade_no": trade.out_trade_no,
        "trade_status": trade.trade_status,
        "total_amount": trade.total_amount,
        "buyer_logon_id": trade.buyer_logon_id,
        "buyer_pay_amount": trade.buyer_pay_amount,
        "send_pay_date": trade.send_pay_date,
    });

    serde_json::to_string(&output).map_err(|e| format!("Failed to serialize output: {e}"))
}

fn query_refund(params: &Params) -> Result<String, String> {
    let has_trade_no = params.trade_no.as_ref().map_or(false, |s| !s.is_empty());
    let has_out_trade_no = params.out_trade_no.as_ref().map_or(false, |s| !s.is_empty());

    if !has_trade_no && !has_out_trade_no {
        return Err("Either 'trade_no' or 'out_trade_no' is required for query_refund".into());
    }

    let out_request_no = params
        .out_request_no
        .as_deref()
        .ok_or("'out_request_no' is required for query_refund")?;

    if out_request_no.is_empty() {
        return Err("'out_request_no' must not be empty".into());
    }

    let mut biz_content = serde_json::Map::new();
    if let Some(ref trade_no) = params.trade_no {
        if !trade_no.is_empty() {
            biz_content.insert("trade_no".into(), serde_json::json!(trade_no));
        }
    }
    if let Some(ref out_trade_no) = params.out_trade_no {
        if !out_trade_no.is_empty() {
            biz_content.insert("out_trade_no".into(), serde_json::json!(out_trade_no));
        }
    }
    biz_content.insert("out_request_no".into(), serde_json::json!(out_request_no));

    let body = serde_json::json!({
        "method": "alipay.trade.fastpay.refund.query",
        "charset": "utf-8",
        "format": "JSON",
        "version": "1.0",
        "biz_content": serde_json::to_string(&biz_content)
            .map_err(|e| format!("Failed to serialize biz_content: {e}"))?,
    });

    let resp_body = alipay_request(&body)?;
    let resp: AlipayGatewayResponse =
        serde_json::from_str(&resp_body).map_err(|e| format!("Failed to parse response: {e}"))?;

    let refund = resp.alipay_trade_fastpay_refund_query_response
        .ok_or("Missing refund query response from Alipay")?;

    if refund.code.as_deref() != Some("10000") {
        let sub_msg = refund.sub_msg.unwrap_or_default();
        let msg = refund.msg.unwrap_or_default();
        return Err(format!("Alipay refund query failed: {} - {}", msg, sub_msg));
    }

    let output = serde_json::json!({
        "action": "query_refund",
        "trade_no": refund.trade_no,
        "out_trade_no": refund.out_trade_no,
        "out_request_no": refund.out_request_no,
        "refund_status": refund.refund_status,
        "total_amount": refund.total_amount,
        "refund_amount": refund.refund_amount,
        "refund_reason": refund.refund_reason,
    });

    serde_json::to_string(&output).map_err(|e| format!("Failed to serialize output: {e}"))
}

fn alipay_request(body: &serde_json::Value) -> Result<String, String> {
    let headers = serde_json::json!({
        "Content-Type": "application/x-www-form-urlencoded;charset=utf-8",
        "Accept": "application/json",
        "User-Agent": "IronClaw-Alipay-Tool/0.1"
    });

    let mut attempt = 0;
    loop {
        attempt += 1;

        let body_bytes = body.to_string().into_bytes();
        let resp = near::agent::host::http_request(
            "POST",
            GATEWAY_URL,
            &headers.to_string(),
            Some(&body_bytes),
            None,
        )
        .map_err(|e| format!("HTTP request failed: {e}"))?;

        if resp.status >= 200 && resp.status < 300 {
            return String::from_utf8(resp.body)
                .map_err(|e| format!("Invalid UTF-8 response: {e}"));
        }

        if attempt < MAX_RETRIES && (resp.status == 429 || resp.status >= 500) {
            near::agent::host::log(
                near::agent::host::LogLevel::Warn,
                &format!(
                    "Alipay API error {} (attempt {}/{}). Retrying...",
                    resp.status, attempt, MAX_RETRIES
                ),
            );
            continue;
        }

        let body_str = String::from_utf8_lossy(&resp.body);
        return Err(format!(
            "Alipay API error (HTTP {}): {}",
            resp.status, body_str
        ));
    }
}

const SCHEMA: &str = r#"{
    "type": "object",
    "properties": {
        "action": {
            "type": "string",
            "description": "The action to perform: 'query_trade' (查询交易状态), 'query_refund' (查询退款状态)",
            "enum": ["query_trade", "query_refund"]
        },
        "trade_no": {
            "type": "string",
            "description": "Alipay trade number (支付宝交易号, either trade_no or out_trade_no required)"
        },
        "out_trade_no": {
            "type": "string",
            "description": "Merchant order number (商户订单号, either trade_no or out_trade_no required)"
        },
        "out_request_no": {
            "type": "string",
            "description": "Refund request number (退款请求号, required for query_refund)"
        }
    },
    "required": ["action"],
    "additionalProperties": false
}"#;

export!(AlipayTool);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_trade_query_response() {
        let json = r#"{
            "alipay_trade_query_response": {
                "code": "10000",
                "msg": "Success",
                "trade_no": "2025010122001400001234567890",
                "out_trade_no": "ORDER_20250101_001",
                "trade_status": "TRADE_SUCCESS",
                "total_amount": "99.99",
                "buyer_logon_id": "138****1234",
                "buyer_pay_amount": "99.99",
                "send_pay_date": "2025-01-01 12:00:00"
            },
            "sign": "ABCDEF123456"
        }"#;
        let resp: AlipayGatewayResponse = serde_json::from_str(json).unwrap();
        let trade = resp.alipay_trade_query_response.unwrap();
        assert_eq!(trade.code.as_deref(), Some("10000"));
        assert_eq!(trade.trade_status.as_deref(), Some("TRADE_SUCCESS"));
        assert_eq!(trade.total_amount.as_deref(), Some("99.99"));
        assert_eq!(trade.buyer_logon_id.as_deref(), Some("138****1234"));
    }

    #[test]
    fn test_parse_refund_query_response() {
        let json = r#"{
            "alipay_trade_fastpay_refund_query_response": {
                "code": "10000",
                "msg": "Success",
                "trade_no": "2025010122001400001234567890",
                "out_trade_no": "ORDER_20250101_001",
                "out_request_no": "REFUND_001",
                "refund_status": "REFUND_SUCCESS",
                "total_amount": "99.99",
                "refund_amount": "50.00",
                "refund_reason": "用户退款"
            },
            "sign": "ABCDEF123456"
        }"#;
        let resp: AlipayGatewayResponse = serde_json::from_str(json).unwrap();
        let refund = resp.alipay_trade_fastpay_refund_query_response.unwrap();
        assert_eq!(refund.code.as_deref(), Some("10000"));
        assert_eq!(refund.refund_status.as_deref(), Some("REFUND_SUCCESS"));
        assert_eq!(refund.refund_amount.as_deref(), Some("50.00"));
        assert_eq!(refund.refund_reason.as_deref(), Some("用户退款"));
    }

    #[test]
    fn test_parse_trade_query_error() {
        let json = r#"{
            "alipay_trade_query_response": {
                "code": "40004",
                "msg": "Business Failed",
                "sub_code": "ACQ.TRADE_NOT_EXIST",
                "sub_msg": "交易不存在"
            },
            "sign": "ABCDEF123456"
        }"#;
        let resp: AlipayGatewayResponse = serde_json::from_str(json).unwrap();
        let trade = resp.alipay_trade_query_response.unwrap();
        assert_eq!(trade.code.as_deref(), Some("40004"));
        assert_eq!(trade.sub_code.as_deref(), Some("ACQ.TRADE_NOT_EXIST"));
        assert_eq!(trade.sub_msg.as_deref(), Some("交易不存在"));
    }

    #[test]
    fn test_parse_empty_gateway_response() {
        let json = r#"{"sign": "ABC123"}"#;
        let resp: AlipayGatewayResponse = serde_json::from_str(json).unwrap();
        assert!(resp.alipay_trade_query_response.is_none());
        assert!(resp.alipay_trade_fastpay_refund_query_response.is_none());
    }
}
