//! Build-time scan of the WebUI static assets.
//!
//! Builds the Vite frontend into Cargo's `OUT_DIR` (unless `SKIP_FRONTEND_BUILD`
//! is set), then emits Rust source that declares one `ASSETS` slice keyed by
//! URL path (relative to the gateway root). Each entry pairs an
//! `include_bytes!` reference with content type and a weak ETag. The static
//! router owns response cache policy because it is request-contextual.
//!
//! The generated source is included from `src/assets.rs`.

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;

use sha2::{Digest, Sha256};

const PINNED_PNPM_PACKAGE: &str = "pnpm@11.7.0";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()); // safety: build script — Cargo always sets this
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap()); // safety: build script — Cargo always sets this
    let generated_dist_dir = out_dir.join("webui-v2-frontend-dist");

    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/pnpm-lock.yaml");
    println!("cargo:rerun-if-changed=frontend/pnpm-workspace.yaml");
    println!("cargo:rerun-if-changed=frontend/packages");
    println!("cargo:rerun-if-changed=frontend/public");
    println!("cargo:rerun-if-changed=frontend/src");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=SKIP_FRONTEND_BUILD");

    // The WebChat v2 route surface + SPA bundle is folded unconditionally into
    // this crate (it is the whole reason `ironclaw_webui` exists), so the
    // frontend is always built. `SKIP_FRONTEND_BUILD=1` is the one opt-out, for
    // environments with no Node/pnpm toolchain (backend-only dev, docs.rs,
    // minimal CI images); the Rust crate still compiles, it just embeds no SPA
    // assets.
    let webui_enabled = env::var_os("SKIP_FRONTEND_BUILD").is_none();

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if webui_enabled {
        let dist_dir = build_frontend_dist(&manifest_dir, &generated_dist_dir)?;
        validate_frontend_dist(&dist_dir);
        collect(&dist_dir, &dist_dir, "", &mut entries)?;
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("// @generated by build.rs — DO NOT EDIT BY HAND\n\n");
    src.push_str("pub(crate) const ASSETS: &[(&str, Asset)] = &[\n");

    let mut index_html_abs: Option<PathBuf> = None;
    for (rel_url, abs_path) in &entries {
        if rel_url == "index.html" {
            index_html_abs = Some(abs_path.clone());
            // index.html is served via a dedicated nonce-substituting
            // path; it is not exposed in the asset table to keep the
            // dispatcher's invariants (raw assets are byte-identical
            // to disk; only the HTML template carries placeholders).
            continue;
        }
        let content_type = content_type_for(abs_path);
        let bytes = fs::read(abs_path)?;
        let etag = weak_etag(&bytes);
        let include_path = abs_path.to_string_lossy();
        src.push_str(&format!(
            "    (\"{}\", Asset {{ bytes: include_bytes!(r\"{}\"), content_type: {:?}, etag: {:?} }}),\n",
            escape_url(rel_url),
            include_path,
            content_type,
            etag,
        ));
    }
    src.push_str("];\n\n");

    if !webui_enabled {
        src.push_str("pub(crate) const INDEX_HTML_TEMPLATE: &str = \"\";\n");
    } else if let Some(path) = index_html_abs {
        src.push_str(&format!(
            "pub(crate) const INDEX_HTML_TEMPLATE: &str = include_str!(r\"{}\");\n",
            path.to_string_lossy(),
        ));
    } else {
        panic!("Vite frontend build output index.html is required");
    }

    fs::write(out_dir.join("assets_generated.rs"), src)?;
    Ok(())
}

fn build_frontend_dist(
    manifest_dir: &Path,
    generated_dist_dir: &Path,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let frontend_dir = manifest_dir.join("frontend");
    if generated_dist_dir.exists() {
        fs::remove_dir_all(generated_dist_dir)?;
    }
    run_pnpm(&["install", "--frozen-lockfile"], &frontend_dir)?;
    let generated_arg = generated_dist_dir.to_string_lossy().into_owned();
    run_pnpm(
        &[
            "exec",
            "vite",
            "build",
            "--outDir",
            &generated_arg,
            "--emptyOutDir",
        ],
        &frontend_dir,
    )?;
    Ok(generated_dist_dir.to_path_buf())
}

fn validate_frontend_dist(dist_dir: &Path) {
    let missing = required_frontend_dist_files(dist_dir)
        .into_iter()
        .filter(|path| !path.is_file())
        .map(|path| path.display().to_string())
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        panic!(
            "WebUI v2 frontend build output is missing required files:\n  {}",
            missing.join("\n  "),
        );
    }
}

fn required_frontend_dist_files(dist_dir: &Path) -> [PathBuf; 3] {
    [
        dist_dir.join("index.html"),
        dist_dir.join("wallet-connect.html"),
        dist_dir.join("wallet-connect.js"),
    ]
}

fn run_command<S: AsRef<str>>(
    command: &str,
    args: &[S],
    cwd: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let rendered = render_command(command, args);
    let status = Command::new(command)
        .args(args.iter().map(AsRef::as_ref))
        .current_dir(cwd)
        .status()?;
    if status.success() {
        return Ok(());
    }

    Err(std::io::Error::other(format!(
        "`{rendered}` failed in {} with status {status}",
        cwd.display(),
    ))
    .into())
}

fn run_pnpm(args: &[&str], cwd: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut corepack_args = Vec::with_capacity(args.len() + 1);
    corepack_args.push("pnpm");
    corepack_args.extend_from_slice(args);
    match run_command(corepack_command(), &corepack_args, cwd) {
        Ok(()) => Ok(()),
        Err(error) if is_not_found_error(error.as_ref()) => {
            eprintln!(
                "`{}` was not found; falling back to `npm exec --yes --package={}`",
                corepack_command(),
                PINNED_PNPM_PACKAGE,
            );
            let mut npm_args = Vec::with_capacity(args.len() + 5);
            npm_args.push("exec".to_string());
            npm_args.push("--yes".to_string());
            npm_args.push(format!("--package={PINNED_PNPM_PACKAGE}"));
            npm_args.push("--".to_string());
            npm_args.push("pnpm".to_string());
            npm_args.extend(args.iter().map(|arg| (*arg).to_string()));
            run_command(npm_command(), &npm_args, cwd).map_err(|fallback_error| {
                io::Error::other(format!(
                    "failed to run pnpm through `{}` or `{}`. Install Corepack/pnpm \
                     (`corepack enable pnpm`) or set SKIP_FRONTEND_BUILD=1 for a \
                     backend-only Rust build. corepack error: {error}; npm fallback \
                     error: {fallback_error}",
                    corepack_command(),
                    npm_command(),
                ))
                .into()
            })
        }
        Err(error) => Err(error),
    }
}

fn corepack_command() -> &'static str {
    if cfg!(windows) {
        "corepack.cmd"
    } else {
        "corepack"
    }
}

fn npm_command() -> &'static str {
    if cfg!(windows) { "npm.cmd" } else { "npm" }
}

fn is_not_found_error(error: &(dyn std::error::Error + 'static)) -> bool {
    error
        .downcast_ref::<io::Error>()
        .is_some_and(|error| error.kind() == io::ErrorKind::NotFound)
}

fn render_command<S: AsRef<str>>(command: &str, args: &[S]) -> String {
    std::iter::once(command)
        .chain(args.iter().map(AsRef::as_ref))
        .collect::<Vec<_>>()
        .join(" ")
}

fn collect(
    root: &Path,
    dir: &Path,
    url_prefix: &str,
    out: &mut Vec<(String, PathBuf)>,
) -> std::io::Result<()> {
    let read_dir = fs::read_dir(dir)?;
    for entry in read_dir {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            if path.file_name().and_then(|name| name.to_str()) == Some(".vite") {
                continue;
            }
            collect(root, &path, url_prefix, out)?;
        } else if file_type.is_file() {
            let rel = path.strip_prefix(root).expect("strip prefix"); // safety: build script — strip_prefix only fails on a logic bug
            // Force forward slashes in the URL key even on Windows hosts.
            let url = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            let url = if url_prefix.is_empty() {
                url
            } else {
                format!("{url_prefix}/{url}")
            };
            out.push((url, path));
        }
    }
    Ok(())
}

fn content_type_for(path: &Path) -> &'static str {
    match path.extension().and_then(|s| s.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        Some("webmanifest") => "application/manifest+json",
        Some("json") => "application/json",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("txt") | Some("md") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn weak_etag(bytes: &[u8]) -> String {
    // Use a content digest, not the Vite filename, so a reused output path
    // still receives a new validator. It remains weak because compression
    // changes the transferred representation while preserving semantics.
    const HEX_DIGITS: &[u8; 16] = b"0123456789abcdef";
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest.as_slice() {
        hex.push(HEX_DIGITS[(byte >> 4) as usize] as char);
        hex.push(HEX_DIGITS[(byte & 0x0f) as usize] as char);
    }
    format!("W/\"sha256-{hex}\"")
}

fn escape_url(s: &str) -> String {
    // URL paths in our static tree are limited to filename chars; the
    // only thing we need to defend against in the emitted source is a
    // literal `"` or `\`. Neither appears in disk file names by
    // convention, but escape defensively.
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
