#!/usr/bin/env python3
"""Generate architecture-map facts and draft Mermaid/Markdown.

This script is deliberately factual and conservative. It extracts changed
crate/module/interface facts from Git snapshots, writes draft architecture
maps, and leaves semantic explanation/refinement to Claude Code in CI.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile
import unittest
from dataclasses import dataclass
from typing import Any


REPO_ROOT = pathlib.Path(
    os.environ.get("ARCH_MAP_REPO_ROOT", pathlib.Path(__file__).resolve().parent.parent)
).resolve()
REPO_ARCH_DOC = pathlib.Path("docs/architecture/ARCHITECTURE.md")
ARCH_SECTION_START = "<!-- architecture-map:start -->"
ARCH_SECTION_END = "<!-- architecture-map:end -->"
GENERATED_MARKER = "<!-- generated by scripts/architecture_map.py; refined by Claude Code in CI -->"
MAX_PR_INTERFACE_LINES = 80
MAX_PR_MERMAID_ITEM_NODES = 40
MAX_OWNER_INTERFACE_ITEMS = 24
MAX_OWNER_MODULE_NODES = 18
MAX_OWNER_IMPL_EDGES = 18

RUST_ITEM_RE = re.compile(
    r"^\s*(?P<vis>pub(?:\([^)]*\))?\s+)?"
    r"(?P<kind>trait|struct|enum|type)\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\b"
)
RUST_IMPL_RE = re.compile(
    r"^\s*impl(?:\s*<[^>]+>)?\s+"
    r"(?:(?P<trait>[A-Za-z_][A-Za-z0-9_:<>]*)\s+for\s+)?"
    r"(?P<target>[A-Za-z_][A-Za-z0-9_:<>]*)"
)
RUST_METHOD_RE = re.compile(
    r"^\s*(?P<vis>pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\("
)
CRATE_NAME_RE = re.compile(r'^\s*name\s*=\s*"([^"]+)"\s*$', re.MULTILINE)
PATH_DEP_RE = re.compile(r'^\s*([A-Za-z0-9_-]+)\s*=\s*\{[^}]*path\s*=\s*"([^"]+)"', re.MULTILINE)
ARCH_SENSITIVE_PARTS = {
    "agent",
    "auth",
    "bridge",
    "channels",
    "config",
    "db",
    "extensions",
    "gateway",
    "hooks",
    "llm",
    "mcp",
    "orchestrator",
    "process",
    "resources",
    "runtime",
    "sandbox",
    "secrets",
    "setup",
    "tools",
    "wasm",
    "workspace",
}


@dataclass(frozen=True)
class RustItem:
    name: str
    kind: str
    public: bool
    line: int


@dataclass(frozen=True)
class RustImpl:
    target: str
    trait_name: str | None
    line: int


@dataclass(frozen=True)
class RustMethod:
    name: str
    public: bool
    line: int


def run_git(args: list[str], cwd: pathlib.Path = REPO_ROOT) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout


def changed_files(base: str, head: str) -> list[str]:
    output = run_git(["diff", "--name-only", f"{base}...{head}"])
    return [line.strip() for line in output.splitlines() if line.strip()]


def read_blob(ref: str, rel_path: str) -> str:
    try:
        return run_git(["show", f"{ref}:{rel_path}"])
    except subprocess.CalledProcessError:
        return ""


def parse_rust_source(source: str) -> dict[str, list[dict[str, Any]]]:
    items: list[RustItem] = []
    impls: list[RustImpl] = []
    methods: list[RustMethod] = []
    for line_number, line in enumerate(source.splitlines(), start=1):
        if item_match := RUST_ITEM_RE.match(line):
            items.append(
                RustItem(
                    name=item_match.group("name"),
                    kind=item_match.group("kind"),
                    public=bool(item_match.group("vis")),
                    line=line_number,
                )
            )
            continue
        if impl_match := RUST_IMPL_RE.match(line):
            impls.append(
                RustImpl(
                    target=impl_match.group("target"),
                    trait_name=impl_match.group("trait"),
                    line=line_number,
                )
            )
            continue
        if method_match := RUST_METHOD_RE.match(line):
            methods.append(
                RustMethod(
                    name=method_match.group("name"),
                    public=bool(method_match.group("vis")),
                    line=line_number,
                )
            )
    return {
        "items": [item.__dict__ for item in items],
        "impls": [impl.__dict__ for impl in impls],
        "methods": [method.__dict__ for method in methods],
    }


def list_files_at_ref(ref: str) -> list[str]:
    try:
        output = run_git(["ls-tree", "-r", "--name-only", ref])
    except subprocess.CalledProcessError:
        return []
    return [line.strip() for line in output.splitlines() if line.strip()]


def is_package_manifest_path(path: str) -> bool:
    return (
        path == "Cargo.toml"
        or (path.startswith("crates/") and path.endswith("/Cargo.toml"))
        or (path.startswith("channels-src/") and path.endswith("/Cargo.toml"))
        or (path.startswith("tools-src/") and path.endswith("/Cargo.toml"))
    )


def discover_workspace_crates(ref: str | None = None) -> dict[str, dict[str, Any]]:
    crates: dict[str, dict[str, Any]] = {}
    if ref:
        manifests = [
            pathlib.Path(path)
            for path in list_files_at_ref(ref)
            if is_package_manifest_path(path)
        ]
    else:
        manifests = [
            pathlib.Path("Cargo.toml"),
            *[path.relative_to(REPO_ROOT) for path in sorted((REPO_ROOT / "crates").glob("*/Cargo.toml"))],
            *[path.relative_to(REPO_ROOT) for path in sorted((REPO_ROOT / "channels-src").glob("*/Cargo.toml"))],
            *[path.relative_to(REPO_ROOT) for path in sorted((REPO_ROOT / "tools-src").glob("*/Cargo.toml"))],
        ]

    for rel_manifest in manifests:
        if ref:
            text = read_blob(ref, rel_manifest.as_posix())
        else:
            manifest = REPO_ROOT / rel_manifest
            if not manifest.exists():
                continue
            text = manifest.read_text(encoding="utf-8")
        if not text:
            continue
        name_match = CRATE_NAME_RE.search(text)
        if not name_match:
            continue
        crate_dir = rel_manifest.parent
        if crate_dir == pathlib.Path("."):
            crate_dir = pathlib.Path("")
        dependencies: list[str] = []
        for dep_match in PATH_DEP_RE.finditer(text):
            dependencies.append(dep_match.group(1).replace("-", "_"))
        name = name_match.group(1)
        crates[name] = {
            "name": name,
            "manifest": str(rel_manifest),
            "path": str(crate_dir) if str(crate_dir) != "." else "",
            "dependencies": sorted(set(dependencies)),
        }
    return crates


def crate_for_path(rel_path: str, crates: dict[str, dict[str, Any]]) -> str | None:
    path = pathlib.Path(rel_path)
    best: tuple[int, str] | None = None
    for crate_name, crate in crates.items():
        crate_path = pathlib.Path(crate["path"])
        if not crate_path.parts:
            continue
        try:
            path.relative_to(crate_path)
        except ValueError:
            continue
        score = len(crate_path.parts)
        if best is None or score > best[0]:
            best = (score, crate_name)
    if best:
        return best[1]
    if rel_path.startswith("src/") or rel_path in {"Cargo.toml", "Cargo.lock"}:
        return "ironclaw"
    return None


def item_key(item: dict[str, Any]) -> tuple[str, str]:
    return item["kind"], item["name"]


def summarize_file_delta(base_source: str, head_source: str) -> dict[str, Any]:
    base = parse_rust_source(base_source)
    head = parse_rust_source(head_source)
    base_items = {item_key(item): item for item in base["items"]}
    head_items = {item_key(item): item for item in head["items"]}
    base_methods = {(method["name"], method["public"]) for method in base["methods"]}
    head_methods = {(method["name"], method["public"]) for method in head["methods"]}

    return {
        "added_items": [head_items[key] for key in sorted(head_items.keys() - base_items.keys())],
        "removed_items": [base_items[key] for key in sorted(base_items.keys() - head_items.keys())],
        "visibility_changed_items": [
            head_items[key]
            for key in sorted(head_items.keys() & base_items.keys())
            if head_items[key]["public"] != base_items[key]["public"]
        ],
        "added_public_methods": [
            {"name": name, "public": public}
            for name, public in sorted(head_methods - base_methods)
            if public
        ],
        "removed_public_methods": [
            {"name": name, "public": public}
            for name, public in sorted(base_methods - head_methods)
            if public
        ],
        "head_items": head["items"],
        "head_impls": head["impls"],
    }


def owner_roots_for_path(rel_path: str, crate_name: str | None, crates: dict[str, dict[str, Any]]) -> list[str]:
    path = pathlib.Path(rel_path)
    roots: list[pathlib.Path] = []
    if crate_name and crate_name in crates:
        crate_path = pathlib.Path(crates[crate_name]["path"])
        if crate_path.parts:
            roots.append(crate_path)
    if path.parts and path.parts[0] == "src" and len(path.parts) >= 3:
        roots.append(pathlib.Path(path.parts[0]) / path.parts[1])
    if path.parts and path.parts[0] in {"channels-src", "tools-src"} and len(path.parts) >= 3:
        roots.append(pathlib.Path(path.parts[0]) / path.parts[1])

    if path.suffix == ".rs" and len(path.parts) > 2:
        parent = path.parent
        if is_complex_module_dir(parent):
            roots.append(parent)

    deduped: list[str] = []
    seen: set[str] = set()
    for root in roots:
        value = root.as_posix()
        if value and value not in seen:
            seen.add(value)
            deduped.append(value)
    return deduped


def is_complex_module_dir(directory: pathlib.Path) -> bool:
    if not directory.parts:
        return False
    absolute = REPO_ROOT / directory
    if not absolute.is_dir():
        return any(part in ARCH_SENSITIVE_PARTS for part in directory.parts)
    rust_files = [path for path in absolute.glob("*.rs") if path.name != "mod.rs"]
    has_local_guidance = any((absolute / name).exists() for name in ("CLAUDE.md", "README.md", "ARCHITECTURE.md"))
    sensitive = any(part in ARCH_SENSITIVE_PARTS for part in directory.parts)
    has_tests = any(path.name.endswith("_test.rs") or path.name == "tests.rs" for path in rust_files)
    return len(rust_files) >= 3 or has_local_guidance or (sensitive and len(rust_files) >= 2) or has_tests


def architecture_doc_for_owner(owner: str) -> str:
    return (pathlib.Path(owner) / "ARCHITECTURE.md").as_posix()


def safe_owner_id(owner: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "__", owner).strip("_")
    return safe or "root"


def snapshot_owner(owner: str, head: str) -> dict[str, Any]:
    files = [
        path
        for path in list_files_at_ref(head)
        if path.startswith(f"{owner}/") and path.endswith(".rs")
    ]
    public_items: dict[tuple[str, str], dict[str, Any]] = {}
    impl_edges: list[tuple[str, str]] = []
    modules: set[str] = set()
    for path in files:
        modules.add(pathlib.Path(path).parent.as_posix())
        parsed = parse_rust_source(read_blob(head, path))
        for item in parsed["items"]:
            if item.get("public"):
                public_items[item_key(item)] = item
        for impl in parsed["impls"]:
            if impl.get("trait_name"):
                impl_edges.append((impl["target"], impl["trait_name"]))
    return {
        "files": files,
        "modules": sorted(modules),
        "public_items": sorted(public_items.values(), key=lambda value: (value["kind"], value["name"])),
        "impl_edges": [{"target": target, "trait": trait} for target, trait in sorted(set(impl_edges))],
    }


def extract_facts(base: str, head: str) -> dict[str, Any]:
    crates = discover_workspace_crates(head)
    all_changed = changed_files(base, head)
    rust_files = [path for path in all_changed if path.endswith(".rs")]
    file_facts: list[dict[str, Any]] = []
    touched_crates: set[str] = set()
    owner_roots: set[str] = set()

    for rel_path in rust_files:
        crate_name = crate_for_path(rel_path, crates)
        if crate_name:
            touched_crates.add(crate_name)
        owners = owner_roots_for_path(rel_path, crate_name, crates)
        owner_roots.update(owners)
        file_facts.append(
            {
                "path": rel_path,
                "crate": crate_name,
                "owners": owners,
                **summarize_file_delta(read_blob(base, rel_path), read_blob(head, rel_path)),
            }
        )

    for rel_path in all_changed:
        crate_name = crate_for_path(rel_path, crates)
        if crate_name:
            touched_crates.add(crate_name)
            owner_roots.update(owner_roots_for_path(rel_path, crate_name, crates))

    owner_snapshots = {owner: snapshot_owner(owner, head) for owner in sorted(owner_roots)}

    return {
        "schema_version": 1,
        "base": base,
        "head": head,
        "changed_files": all_changed,
        "touched_crates": sorted(touched_crates),
        "owners": sorted(owner_roots),
        "architecture_docs": [REPO_ARCH_DOC.as_posix(), *[architecture_doc_for_owner(owner) for owner in sorted(owner_roots)]],
        "crates": crates,
        "owner_snapshots": owner_snapshots,
        "files": file_facts,
    }


def mermaid_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"n_{cleaned}"
    return cleaned


def item_label(item: dict[str, Any]) -> str:
    public = "pub " if item.get("public") else ""
    return f"{public}{item['kind']} {item['name']}"


def render_diff_mermaid(facts: dict[str, Any]) -> str:
    lines = ["```mermaid", "flowchart TD"]
    touched = facts.get("touched_crates", [])
    if not touched:
        lines.append('  no_arch_change["No crate-level architecture changes detected"]')
    for crate_name in touched:
        lines.append(f'  {mermaid_id(crate_name)}["{crate_name}"]:::changed')

    added_count = 0
    removed_count = 0
    overflow_count = 0
    for file_fact in facts.get("files", []):
        crate_name = file_fact.get("crate") or "unknown"
        crate_node = mermaid_id(crate_name)
        for item in file_fact.get("added_items", []):
            if not item.get("public"):
                continue
            if added_count + removed_count >= MAX_PR_MERMAID_ITEM_NODES:
                overflow_count += 1
                continue
            node = f"{crate_node}_added_{added_count}"
            added_count += 1
            lines.append(f'  {node}["{item_label(item)}"]:::added')
            lines.append(f"  {crate_node} --> {node}")
        for item in file_fact.get("removed_items", []):
            if not item.get("public"):
                continue
            if added_count + removed_count >= MAX_PR_MERMAID_ITEM_NODES:
                overflow_count += 1
                continue
            node = f"{crate_node}_removed_{removed_count}"
            removed_count += 1
            lines.append(f'  {node}["{item_label(item)}"]:::removed')
            lines.append(f"  {crate_node} -. removed .-> {node}")
    if overflow_count:
        lines.append(f'  overflow["{overflow_count} more public item changes in facts.json"]:::changed')

    for crate_name in touched:
        deps = facts["crates"].get(crate_name, {}).get("dependencies", [])
        for dep in deps:
            if dep in facts["crates"]:
                lines.append(f"  {mermaid_id(crate_name)} --> {mermaid_id(dep)}")

    lines.extend(
        [
            "  classDef added fill:#d8f5d0,stroke:#2f7d32,color:#111",
            "  classDef changed fill:#fff2b8,stroke:#8a6d00,color:#111",
            "  classDef removed fill:#ffd6d6,stroke:#b3261e,color:#111",
            "```",
        ]
    )
    return "\n".join(lines)


def summarize_interface_delta(facts: dict[str, Any]) -> list[str]:
    summary: list[str] = []
    for file_fact in facts.get("files", []):
        path = file_fact["path"]
        for item in file_fact.get("added_items", []):
            if not item.get("public"):
                continue
            summary.append(f"- Added `{item_label(item)}` in `{path}`")
        for item in file_fact.get("removed_items", []):
            if not item.get("public"):
                continue
            summary.append(f"- Removed `{item_label(item)}` from `{path}`")
        for method in file_fact.get("added_public_methods", []):
            summary.append(f"- Added public method `{method['name']}(...)` in `{path}`")
        for method in file_fact.get("removed_public_methods", []):
            summary.append(f"- Removed public method `{method['name']}(...)` from `{path}`")
    if len(summary) > MAX_PR_INTERFACE_LINES:
        overflow = len(summary) - MAX_PR_INTERFACE_LINES
        summary = summary[:MAX_PR_INTERFACE_LINES]
        summary.append(f"- ... and {overflow} more public interface changes in `facts.json`.")
    return summary or ["- No public Rust item changes detected by the deterministic extractor."]


def render_pr_section(facts: dict[str, Any]) -> str:
    lines = [
        ARCH_SECTION_START,
        "## Architecture Impact",
        "",
        "### What changed",
        "Claude Code will refine this section from the deterministic facts and changed code.",
        "",
        "### Changed scopes",
    ]
    owners = facts.get("owners", [])
    lines.extend(f"- `{owner}`" for owner in owners)
    if not owners:
        lines.append("- No architecture owner root detected.")
    lines.extend(["", "### Interface delta"])
    lines.extend(summarize_interface_delta(facts))
    lines.extend(["", "### Visual diff", "", render_diff_mermaid(facts), "", "### Updated maps"])
    lines.extend(f"- `{doc}`" for doc in facts.get("architecture_docs", []))
    lines.extend(
        [
            "",
            f"_Extractor input: `{len(facts.get('changed_files', []))}` changed file(s), `{len(owners)}` architecture owner(s)._",
            ARCH_SECTION_END,
        ]
    )
    return "\n".join(lines)


def render_repo_doc(facts: dict[str, Any]) -> str:
    crates = facts.get("crates", {})
    lines = [
        "# Repository Architecture Map",
        "",
        GENERATED_MARKER,
        "",
        "This map shows repository-level crate and subsystem relationships. It is generated from workspace manifests and refined by Claude Code when the architecture-map workflow runs.",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for crate_name in sorted(crates):
        lines.append(f'  {mermaid_id(crate_name)}["{crate_name}"]')
    for crate_name, crate in sorted(crates.items()):
        for dep in crate.get("dependencies", []):
            if dep in crates:
                lines.append(f"  {mermaid_id(crate_name)} --> {mermaid_id(dep)}")
    lines.extend(["```", "", "## Crates", ""])
    for crate_name, crate in sorted(crates.items()):
        deps = ", ".join(f"`{dep}`" for dep in crate.get("dependencies", []) if dep in crates)
        lines.append(f"- `{crate_name}`: `{crate.get('path') or '.'}`; deps: {deps or '(none)'}")
    lines.append("")
    return "\n".join(lines)


def render_owner_doc(owner: str, facts: dict[str, Any]) -> str:
    relevant_files = [
        file_fact for file_fact in facts.get("files", []) if owner in file_fact.get("owners", [])
    ]
    snapshot = facts.get("owner_snapshots", {}).get(owner, {})
    public_items = snapshot.get("public_items", [])
    impl_edges = snapshot.get("impl_edges", [])
    modules = snapshot.get("modules", [])
    shown_items = sorted(public_items, key=lambda value: (value["kind"], value["name"]))[:MAX_OWNER_INTERFACE_ITEMS]
    shown_modules = modules[:MAX_OWNER_MODULE_NODES]
    shown_impl_edges = impl_edges[:MAX_OWNER_IMPL_EDGES]
    item_overflow = max(0, len(public_items) - len(shown_items))
    module_overflow = max(0, len(modules) - len(shown_modules))
    edge_overflow = max(0, len(impl_edges) - len(shown_impl_edges))

    lines = [
        f"# Architecture Map: `{owner}`",
        "",
        GENERATED_MARKER,
        "",
        "This map is a curated architecture summary for this ownership root. The deterministic extractor supplies candidate modules, public interfaces, and implementation edges; Claude Code keeps the diagram and prose at the useful abstraction level for reviewers.",
        "",
        "## Purpose and Ownership",
        "",
        f"- Ownership root: `{owner}`",
        f"- Architecture doc: `{architecture_doc_for_owner(owner)}`",
        "- Claude Code should replace this placeholder with the owner purpose, responsibilities, and what belongs outside this boundary.",
        "",
        "## Architecture Diagram",
        "",
        "```mermaid",
        "flowchart TD",
        f'  owner["{owner}"]',
    ]
    for index, module in enumerate(shown_modules):
        node = f"module_{index}"
        lines.append(f'  {node}["{module}"]')
        lines.append(f"  owner --> {node}")
    if module_overflow:
        lines.append(f'  modules_more["{module_overflow} more module(s) in facts"]')
        lines.append("  owner --> modules_more")
    for index, item in enumerate(sorted(shown_items, key=lambda value: value["name"])):
        node = f"item_{index}"
        lines.append(f'  {node}["{item_label(item)}"]')
        lines.append(f"  owner --> {node}")
    if item_overflow:
        lines.append(f'  items_more["{item_overflow} more public item(s) in facts"]')
        lines.append("  owner --> items_more")
    for index, impl in enumerate(shown_impl_edges):
        target_node = f"impl_target_{index}"
        trait_node = f"impl_trait_{index}"
        lines.append(f'  {target_node}["{impl["target"]}"]')
        lines.append(f'  {trait_node}["{impl["trait"]}"]')
        lines.append(f"  {target_node} -. implements .-> {trait_node}")
    if edge_overflow:
        lines.append(f'  edges_more["{edge_overflow} more implementation edge(s) in facts"]')
        lines.append("  owner -. has .-> edges_more")
    lines.extend(["```", "", "## Important Interfaces", ""])
    if shown_items:
        for item in shown_items:
            lines.append(f"- `{item_label(item)}`")
        if item_overflow:
            lines.append(f"- `{item_overflow}` additional public item(s) were extracted but should only be promoted here if architecturally important.")
    else:
        lines.append("- No public Rust items captured for this owner in the current head snapshot.")

    lines.extend(
        [
            "",
            "## Key Flows",
            "",
            "- Claude Code should describe the main runtime/data/control flow through this owner, grounded in the diagram and changed code.",
            "",
            "## Boundary Rules and Invariants",
            "",
            "- Claude Code should list the non-obvious ownership rules, security boundaries, persistence invariants, or lifecycle constraints reviewers need to preserve.",
            "",
            "## Important Facts Not Shown in Diagram",
            "",
        ]
    )
    if shown_impl_edges:
        for impl in shown_impl_edges:
            lines.append(f"- `{impl['target']}` implements `{impl['trait']}`.")
        if edge_overflow:
            lines.append(f"- `{edge_overflow}` additional implementation edge(s) were extracted but omitted from the diagram draft.")
    else:
        lines.append("- No trait implementation edges were captured for this owner snapshot.")

    lines.extend(["", "## Related Context", ""])
    if modules:
        for module in shown_modules:
            lines.append(f"- Module: `{module}`")
        if module_overflow:
            lines.append(f"- `{module_overflow}` additional module(s) were extracted but omitted from this draft.")
    else:
        lines.append("- No Rust modules captured for this owner in the current head snapshot.")

    lines.extend(["", "## Changed Files", ""])
    if relevant_files:
        lines.extend(f"- `{file_fact['path']}`" for file_fact in relevant_files)
    else:
        lines.append("- No changed files captured.")
    lines.append("")
    return "\n".join(lines)


def owner_shard_records(facts: dict[str, Any], shards_dir: str = ".architecture-map/owners") -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for owner in facts.get("owners", []):
        safe_id = safe_owner_id(owner)
        shard_root = pathlib.Path(shards_dir) / safe_id
        records.append(
            {
                "owner": owner,
                "safe_id": safe_id,
                "architecture_doc": architecture_doc_for_owner(owner),
                "facts_path": (shard_root / "facts.json").as_posix(),
                "prompt_path": (shard_root / "prompt.md").as_posix(),
                "summary_path": (shard_root / "summary.md").as_posix(),
            }
        )
    return records


def owner_facts_for_shard(facts: dict[str, Any], owner: str, architecture_doc: str) -> dict[str, Any]:
    owner_files = [
        file_fact for file_fact in facts.get("files", []) if owner in file_fact.get("owners", [])
    ]
    return {
        "schema_version": facts.get("schema_version"),
        "base": facts.get("base"),
        "head": facts.get("head"),
        "owner": owner,
        "architecture_doc": architecture_doc,
        "repo_architecture_doc": REPO_ARCH_DOC.as_posix(),
        "changed_files": [file_fact.get("path") for file_fact in owner_files],
        "owner_snapshot": facts.get("owner_snapshots", {}).get(owner, {}),
        "files": owner_files,
        "crates": facts.get("crates", {}),
    }


def render_owner_prompt(record: dict[str, str]) -> str:
    return "\n".join(
        [
            f"# Architecture Map Owner Shard: `{record['owner']}`",
            "",
            "Work inside the current checkout only.",
            "",
            "## Inputs",
            "",
            f"- Owner facts: `{record['facts_path']}`",
            f"- Architecture document to refine: `{record['architecture_doc']}`",
            f"- Shard summary to write: `{record['summary_path']}`",
            "- Changed Rust files and nearby `CLAUDE.md`, `README.md`, or existing architecture docs when useful.",
            "",
            "## Task",
            "",
            "- Refine the owner `ARCHITECTURE.md` so it is a curated architecture summary, not an exhaustive public-type dump.",
            "- Keep or redraw the Mermaid diagram at this owner level: top-level crate/package maps show major interfaces/components; source subsystem maps show subsystem modules; complex module maps show local module flow.",
            "- Keep the diagram readable. Move important facts that do not belong visually into prose below the diagram.",
            "- Fill in Purpose and Ownership, Important Interfaces, Key Flows, Boundary Rules and Invariants, Important Facts Not Shown in Diagram, and Related Context.",
            "- Write a concise reviewer-facing summary to the shard summary file.",
            "",
            "## Hard Constraints",
            "",
            f"- Edit only `{record['architecture_doc']}` and `{record['summary_path']}`.",
            "- Do not edit source code, workflows, scripts, Cargo files, tests, migrations, or unrelated docs.",
            "- Do not invent crates, interfaces, owners, or edges not grounded in the facts or source files.",
            "- Prefer fewer important nodes/edges over preserving every extracted Rust item.",
            "",
        ]
    )


def write_owner_shards(
    facts: dict[str, Any],
    output_root: pathlib.Path,
    shards_dir: str = ".architecture-map/owners",
) -> list[dict[str, str]]:
    records = owner_shard_records(facts, shards_dir)
    for record in records:
        facts_path = output_root / record["facts_path"]
        prompt_path = output_root / record["prompt_path"]
        summary_path = output_root / record["summary_path"]
        facts_path.parent.mkdir(parents=True, exist_ok=True)
        facts_path.write_text(
            json.dumps(
                owner_facts_for_shard(facts, record["owner"], record["architecture_doc"]),
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        prompt_path.write_text(render_owner_prompt(record), encoding="utf-8")
        if not summary_path.exists():
            summary_path.write_text(
                f"# Architecture Shard Summary: `{record['owner']}`\n\n"
                "- Claude Code has not refined this owner shard yet.\n",
                encoding="utf-8",
            )
    return records


def owner_matrix(records: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    return {"include": records}


def render_docs(facts: dict[str, Any], output_root: pathlib.Path) -> None:
    repo_doc = output_root / REPO_ARCH_DOC
    repo_doc.parent.mkdir(parents=True, exist_ok=True)
    repo_doc.write_text(render_repo_doc(facts), encoding="utf-8")
    for owner in facts.get("owners", []):
        doc_path = output_root / architecture_doc_for_owner(owner)
        doc_path.parent.mkdir(parents=True, exist_ok=True)
        doc_path.write_text(render_owner_doc(owner, facts), encoding="utf-8")


def replace_marked_section(body: str, section: str) -> str:
    if ARCH_SECTION_START in body and ARCH_SECTION_END in body:
        pattern = re.compile(
            re.escape(ARCH_SECTION_START) + r".*?" + re.escape(ARCH_SECTION_END),
            re.DOTALL,
        )
        return pattern.sub(section, body)
    if body.strip():
        return body.rstrip() + "\n\n" + section + "\n"
    return section + "\n"


def cmd_extract(args: argparse.Namespace) -> int:
    facts = extract_facts(args.base, args.head)
    output = pathlib.Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(facts, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return 0


def cmd_render_docs(args: argparse.Namespace) -> int:
    facts = json.loads(pathlib.Path(args.facts).read_text(encoding="utf-8"))
    render_docs(facts, pathlib.Path(args.output_root))
    return 0


def cmd_render_pr_section(args: argparse.Namespace) -> int:
    facts = json.loads(pathlib.Path(args.facts).read_text(encoding="utf-8"))
    output = pathlib.Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_pr_section(facts) + "\n", encoding="utf-8")
    return 0


def cmd_write_owner_shards(args: argparse.Namespace) -> int:
    facts = json.loads(pathlib.Path(args.facts).read_text(encoding="utf-8"))
    records = write_owner_shards(facts, pathlib.Path(args.output_root), args.shards_dir)
    if args.matrix_out:
        matrix_out = pathlib.Path(args.matrix_out)
        matrix_out.parent.mkdir(parents=True, exist_ok=True)
        matrix_out.write_text(json.dumps(owner_matrix(records), sort_keys=True) + "\n", encoding="utf-8")
    return 0


def cmd_update_pr_body(args: argparse.Namespace) -> int:
    section = pathlib.Path(args.section).read_text(encoding="utf-8").rstrip()
    body_path = pathlib.Path(args.body)
    body = body_path.read_text(encoding="utf-8") if body_path.exists() else ""
    output = pathlib.Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(replace_marked_section(body, section), encoding="utf-8")
    return 0


def cmd_apply(args: argparse.Namespace) -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = pathlib.Path(tmp)
        facts_path = tmp_path / "facts.json"
        facts = extract_facts(args.base, args.head)
        output_root = pathlib.Path(args.output_root)
        render_docs(facts, output_root)
        if args.shards_out:
            facts["owner_shards"] = write_owner_shards(facts, output_root, args.shards_out)
        facts_path.write_text(json.dumps(facts, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if args.pr_section_out:
            pr_section_out = pathlib.Path(args.pr_section_out)
            pr_section_out.parent.mkdir(parents=True, exist_ok=True)
            pr_section_out.write_text(render_pr_section(facts) + "\n", encoding="utf-8")
        if args.facts_out:
            facts_out = pathlib.Path(args.facts_out)
            facts_out.parent.mkdir(parents=True, exist_ok=True)
            facts_out.write_text(facts_path.read_text(encoding="utf-8"), encoding="utf-8")
        if args.owner_matrix_out:
            records = facts.get("owner_shards", owner_shard_records(facts, args.shards_out or ".architecture-map/owners"))
            owner_matrix_out = pathlib.Path(args.owner_matrix_out)
            owner_matrix_out.parent.mkdir(parents=True, exist_ok=True)
            owner_matrix_out.write_text(json.dumps(owner_matrix(records), sort_keys=True) + "\n", encoding="utf-8")
    return 0


def allowed_architecture_outputs(facts: dict[str, Any]) -> set[str]:
    return set(facts.get("architecture_docs", []))


class ArchitectureMapTests(unittest.TestCase):
    def test_parse_rust_source_finds_public_items_and_methods(self) -> None:
        parsed = parse_rust_source(
            """
            pub trait Runner {}
            pub struct Worker;
            enum Hidden {}
            impl Runner for Worker {}
            impl Worker {
                pub async fn run(&self) {}
                fn helper(&self) {}
            }
            """
        )
        self.assertIn({"name": "Runner", "kind": "trait", "public": True, "line": 2}, parsed["items"])
        self.assertIn({"name": "Worker", "kind": "struct", "public": True, "line": 3}, parsed["items"])
        self.assertIn({"target": "Worker", "trait_name": "Runner", "line": 5}, parsed["impls"])
        self.assertIn({"name": "run", "public": True, "line": 7}, parsed["methods"])

    def test_summarize_file_delta_reports_interface_changes(self) -> None:
        delta = summarize_file_delta(
            "pub struct Old;\nimpl Old {\n    pub fn before(&self) {}\n}\n",
            "pub struct New;\nimpl New {\n    pub fn after(&self) {}\n}\n",
        )
        self.assertEqual({item["name"] for item in delta["added_items"]}, {"New"})
        self.assertEqual({item["name"] for item in delta["removed_items"]}, {"Old"})
        self.assertEqual(delta["added_public_methods"], [{"name": "after", "public": True}])

    def test_owner_roots_include_crate_and_complex_module(self) -> None:
        crates = {"example": {"path": "crates/example"}}
        owners = owner_roots_for_path("crates/example/src/runtime/worker.rs", "example", crates)
        self.assertIn("crates/example", owners)
        self.assertIn("crates/example/src/runtime", owners)

    def test_owner_roots_include_dynamic_top_level_src_subsystem(self) -> None:
        crates = {"ironclaw": {"path": ""}}
        owners = owner_roots_for_path("src/new_subsystem/thing.rs", "ironclaw", crates)
        self.assertIn("src/new_subsystem", owners)

    def test_owner_roots_skip_top_level_src_files(self) -> None:
        crates = {"ironclaw": {"path": ""}}
        self.assertNotIn("src/app.rs", owner_roots_for_path("src/app.rs", "ironclaw", crates))
        self.assertNotIn("src/NETWORK_SECURITY.md", owner_roots_for_path("src/NETWORK_SECURITY.md", "ironclaw", crates))

    def test_owner_roots_include_dynamic_channel_and_tool_subsystems(self) -> None:
        owners = owner_roots_for_path("channels-src/new_channel/src/lib.rs", None, {})
        self.assertIn("channels-src/new_channel", owners)
        owners = owner_roots_for_path("tools-src/new_tool/src/lib.rs", None, {})
        self.assertIn("tools-src/new_tool", owners)

    def test_package_manifest_path_includes_channels_and_tools(self) -> None:
        self.assertTrue(is_package_manifest_path("Cargo.toml"))
        self.assertTrue(is_package_manifest_path("crates/ironclaw_common/Cargo.toml"))
        self.assertTrue(is_package_manifest_path("channels-src/slack/Cargo.toml"))
        self.assertTrue(is_package_manifest_path("tools-src/google-drive/Cargo.toml"))
        self.assertFalse(is_package_manifest_path("docs/reborn/Cargo.toml"))

    def test_render_owner_doc_uses_full_owner_snapshot(self) -> None:
        facts = {
            "files": [
                {
                    "path": "crates/example/src/a.rs",
                    "owners": ["crates/example"],
                }
            ],
            "owner_snapshots": {
                "crates/example": {
                    "files": ["crates/example/src/a.rs", "crates/example/src/b.rs"],
                    "modules": ["crates/example/src"],
                    "public_items": [
                        {"kind": "struct", "name": "A", "public": True, "line": 1},
                        {"kind": "struct", "name": "B", "public": True, "line": 1},
                    ],
                    "impl_edges": [],
                }
            },
        }
        doc = render_owner_doc("crates/example", facts)
        self.assertIn("pub struct A", doc)
        self.assertIn("pub struct B", doc)

    def test_render_owner_doc_has_curated_sections(self) -> None:
        facts = {
            "files": [],
            "owner_snapshots": {
                "src/runtime": {
                    "files": ["src/runtime/mod.rs"],
                    "modules": ["src/runtime"],
                    "public_items": [{"kind": "trait", "name": "Runtime", "public": True, "line": 1}],
                    "impl_edges": [{"target": "DefaultRuntime", "trait": "Runtime"}],
                }
            },
        }
        doc = render_owner_doc("src/runtime", facts)
        self.assertIn("## Architecture Diagram", doc)
        self.assertIn("## Important Interfaces", doc)
        self.assertIn("## Key Flows", doc)
        self.assertIn("## Boundary Rules and Invariants", doc)
        self.assertIn("## Important Facts Not Shown in Diagram", doc)

    def test_safe_owner_id_stabilizes_paths(self) -> None:
        self.assertEqual(safe_owner_id("crates/example/src/runtime"), "crates__example__src__runtime")

    def test_write_owner_shards_creates_matrix_and_files(self) -> None:
        facts = {
            "schema_version": 1,
            "base": "base",
            "head": "head",
            "owners": ["crates/example"],
            "owner_snapshots": {"crates/example": {"files": [], "modules": [], "public_items": [], "impl_edges": []}},
            "files": [{"path": "crates/example/src/lib.rs", "owners": ["crates/example"]}],
            "crates": {},
        }
        with tempfile.TemporaryDirectory() as tmp:
            output_root = pathlib.Path(tmp)
            records = write_owner_shards(facts, output_root)
            matrix = owner_matrix(records)
            self.assertEqual(matrix["include"][0]["safe_id"], "crates__example")
            self.assertTrue((output_root / ".architecture-map/owners/crates__example/facts.json").exists())
            self.assertTrue((output_root / ".architecture-map/owners/crates__example/prompt.md").exists())
            self.assertTrue((output_root / ".architecture-map/owners/crates__example/summary.md").exists())

    def test_replace_marked_section_preserves_human_text(self) -> None:
        original = f"Intro\n{ARCH_SECTION_START}\nold\n{ARCH_SECTION_END}\nOutro"
        updated = replace_marked_section(original, f"{ARCH_SECTION_START}\nnew\n{ARCH_SECTION_END}")
        self.assertIn("Intro", updated)
        self.assertIn("new", updated)
        self.assertIn("Outro", updated)
        self.assertNotIn("old", updated)

    def test_render_pr_section_includes_diff_mermaid(self) -> None:
        facts = {
            "changed_files": ["crates/example/src/lib.rs"],
            "owners": ["crates/example"],
            "architecture_docs": ["docs/architecture/ARCHITECTURE.md", "crates/example/ARCHITECTURE.md"],
            "touched_crates": ["example"],
            "crates": {"example": {"dependencies": []}},
            "files": [
                {
                    "path": "crates/example/src/lib.rs",
                    "crate": "example",
                    "owners": ["crates/example"],
                    "added_items": [{"kind": "trait", "name": "Runner", "public": True, "line": 1}],
                    "removed_items": [],
                    "added_public_methods": [],
                    "removed_public_methods": [],
                }
            ],
        }
        section = render_pr_section(facts)
        self.assertIn("```mermaid", section)
        self.assertIn("pub trait Runner", section)
        self.assertIn("crates/example/ARCHITECTURE.md", section)


def cmd_test(_: argparse.Namespace) -> int:
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(ArchitectureMapTests)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    extract = subparsers.add_parser("extract")
    extract.add_argument("--base", required=True)
    extract.add_argument("--head", required=True)
    extract.add_argument("--out", required=True)
    extract.set_defaults(func=cmd_extract)

    render_docs_parser = subparsers.add_parser("render-docs")
    render_docs_parser.add_argument("--facts", required=True)
    render_docs_parser.add_argument("--output-root", default=str(REPO_ROOT))
    render_docs_parser.set_defaults(func=cmd_render_docs)

    render_pr = subparsers.add_parser("render-pr-section")
    render_pr.add_argument("--facts", required=True)
    render_pr.add_argument("--out", required=True)
    render_pr.set_defaults(func=cmd_render_pr_section)

    write_shards = subparsers.add_parser("write-owner-shards")
    write_shards.add_argument("--facts", required=True)
    write_shards.add_argument("--output-root", default=str(REPO_ROOT))
    write_shards.add_argument("--shards-dir", default=".architecture-map/owners")
    write_shards.add_argument("--matrix-out")
    write_shards.set_defaults(func=cmd_write_owner_shards)

    update_body = subparsers.add_parser("update-pr-body")
    update_body.add_argument("--body", required=True)
    update_body.add_argument("--section", required=True)
    update_body.add_argument("--out", required=True)
    update_body.set_defaults(func=cmd_update_pr_body)

    apply = subparsers.add_parser("apply")
    apply.add_argument("--base", required=True)
    apply.add_argument("--head", required=True)
    apply.add_argument("--output-root", default=str(REPO_ROOT))
    apply.add_argument("--facts-out")
    apply.add_argument("--pr-section-out")
    apply.add_argument("--shards-out")
    apply.add_argument("--owner-matrix-out")
    apply.set_defaults(func=cmd_apply)

    test = subparsers.add_parser("test")
    test.set_defaults(func=cmd_test)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
