//! Per-user tool permission system.
//!
//! Each tool has a `PermissionState` that controls whether it runs without
//! confirmation, asks the user each time, or is fully disabled.  A static
//! table of tier defaults (`TOOL_RISK_DEFAULTS`) is used as the fallback when
//! no per-user override exists.

use std::collections::HashMap;
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

/// How a tool may be invoked by the agent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionState {
    /// Run automatically without asking the user first.
    AlwaysAllow,
    /// Pause and ask the user before every invocation.
    AskEachTime,
    /// Refuse to run the tool at all.
    Disabled,
}

/// Static map of built-in tool names → their default `PermissionState`.
///
/// Tools present here default to `AlwaysAllow` (read-only / low-risk) or
/// `AskEachTime` (write / destructive / network).  Tools **absent** from the
/// map fall back to `AskEachTime` in `effective_permission`.
pub static TOOL_RISK_DEFAULTS: LazyLock<HashMap<&'static str, PermissionState>> =
    LazyLock::new(|| {
        let mut m = HashMap::new();

        // --- AlwaysAllow: informational, low-risk, or safe writes ---
        for name in &[
            "echo",
            "time",
            "json",
            "memory_search",
            "memory_read",
            "memory_write",
            "memory_tree",
            "tool_list",
            "tool_info",
            "tool_search",
            "skill_list",
            "skill_search",
            "list_jobs",
            "job_status",
            "job_events",
            "image_analyze",
            "message",
        ] {
            m.insert(*name, PermissionState::AlwaysAllow);
        }

        // --- AskEachTime: write, destructive, code-execution, or network ---
        for name in &[
            "shell",
            "read_file",
            "write_file",
            "list_dir",
            "apply_patch",
            "http",
            "create_job",
            "event_emit",
            "routine_create",
            "routine_update",
            "cancel_job",
            "job_prompt",
            "routine_delete",
            "routine_fire",
            "tool_install",
            "tool_auth",
            "tool_activate",
            "tool_remove",
            "tool_upgrade",
            "skill_install",
            "skill_remove",
            "secret_list",
            "secret_delete",
            "image_generate",
            "image_edit",
            "restart",
            "build_software",
            "tool_permission_set",
        ] {
            m.insert(*name, PermissionState::AskEachTime);
        }

        m
    });

// ---------------------------------------------------------------------------
// Admin tool policy
// ---------------------------------------------------------------------------

/// Well-known `user_id` for admin-scoped settings in the settings table.
///
/// Safe from collision because all real user IDs are UUIDs generated by
/// `Uuid::new_v4()` in both `users_create_handler` and OIDC auto-provisioning.
pub const ADMIN_SETTINGS_USER_ID: &str = "__admin__";

/// Settings key where the admin tool policy is stored.
pub const ADMIN_TOOL_POLICY_KEY: &str = "admin_tool_policy";

/// Admin-defined tool restrictions that override per-user permissions.
///
/// Stored as a single JSON value in the `settings` table under
/// `(ADMIN_SETTINGS_USER_ID, ADMIN_TOOL_POLICY_KEY)`. Tools listed here are
/// stripped from the LLM context before per-user permissions are evaluated,
/// so users cannot re-enable admin-disabled tools.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct AdminToolPolicy {
    /// Tool names disabled for ALL non-admin users.
    #[serde(default)]
    pub disabled_tools: Vec<String>,

    /// Additional tool names disabled for specific users, keyed by `user_id`.
    #[serde(default)]
    pub user_disabled_tools: HashMap<String, Vec<String>>,
}

impl AdminToolPolicy {
    /// Returns `true` if `tool_name` is admin-disabled for the given `user_id`.
    pub fn is_tool_disabled(&self, tool_name: &str, user_id: &str) -> bool {
        if self.disabled_tools.iter().any(|t| t == tool_name) {
            return true;
        }
        if let Some(user_tools) = self.user_disabled_tools.get(user_id) {
            return user_tools.iter().any(|t| t == tool_name);
        }
        false
    }

    /// Returns `true` if the policy has no restrictions at all.
    pub fn is_empty(&self) -> bool {
        self.disabled_tools.is_empty() && self.user_disabled_tools.is_empty()
    }
}

// ---------------------------------------------------------------------------
// Per-user effective permission
// ---------------------------------------------------------------------------

/// Return the effective `PermissionState` for `tool_name`.
///
/// Lookup order:
/// 1. Per-user `overrides` map (highest priority).
/// 2. `TOOL_RISK_DEFAULTS` static table.
/// 3. `AskEachTime` as the safe fallback for any unknown tool.
pub fn effective_permission(
    tool_name: &str,
    overrides: &HashMap<String, PermissionState>,
) -> PermissionState {
    if let Some(state) = overrides.get(tool_name) {
        return *state;
    }
    if let Some(state) = TOOL_RISK_DEFAULTS.get(tool_name) {
        return *state;
    }
    PermissionState::AskEachTime
}

// ---------------------------------------------------------------------------
// Shared admin tool policy filter
// ---------------------------------------------------------------------------

/// Load the admin tool policy from the database and filter out disabled tools.
///
/// Returns the filtered tool list. In non-multi-tenant mode or for admin users,
/// returns the input list unchanged. On DB errors, returns an empty list
/// (fail-closed) to preserve admin restrictions.
pub async fn filter_admin_disabled_tools(
    tool_defs: Vec<crate::llm::ToolDefinition>,
    multi_tenant: bool,
    role: &crate::ownership::UserRole,
    user_id: &str,
    db: Option<&std::sync::Arc<dyn crate::db::Database>>,
) -> Vec<crate::llm::ToolDefinition> {
    // Only enforce in multi-tenant mode for non-admin users.
    if !multi_tenant || *role == crate::ownership::UserRole::Admin {
        return tool_defs;
    }

    let Some(db) = db else {
        return tool_defs;
    };

    let admin_policy: AdminToolPolicy = match db
        .get_setting(ADMIN_SETTINGS_USER_ID, ADMIN_TOOL_POLICY_KEY)
        .await
    {
        Ok(Some(value)) => match serde_json::from_value(value) {
            Ok(policy) => policy,
            Err(e) => {
                tracing::warn!(
                    "Failed to deserialize admin tool policy, returning empty tool list \
                     (fail-closed): {}",
                    e
                );
                return Vec::new();
            }
        },
        Ok(None) => return tool_defs,
        Err(e) => {
            tracing::warn!(
                "Failed to load admin tool policy, returning empty tool list (fail-closed): {}",
                e
            );
            return Vec::new();
        }
    };

    if admin_policy.is_empty() {
        return tool_defs;
    }

    tool_defs
        .into_iter()
        .filter(|def| {
            if admin_policy.is_tool_disabled(&def.name, user_id) {
                tracing::debug!(
                    tool = %def.name,
                    "Excluding tool disabled by admin policy"
                );
                false
            } else {
                true
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::Settings;

    #[test]
    fn test_effective_permission_user_override_wins() {
        let mut overrides = HashMap::new();
        // Override "shell" (default: AskEachTime) to AlwaysAllow.
        overrides.insert("shell".to_string(), PermissionState::AlwaysAllow);

        assert_eq!(
            effective_permission("shell", &overrides),
            PermissionState::AlwaysAllow,
            "user override should take precedence over tier default"
        );
    }

    #[test]
    fn test_effective_permission_tier_default_fallback() {
        let overrides = HashMap::new();

        // "echo" has AlwaysAllow in the defaults table.
        assert_eq!(
            effective_permission("echo", &overrides),
            PermissionState::AlwaysAllow,
            "tier default should be returned when no user override exists"
        );

        // "shell" has AskEachTime in the defaults table.
        assert_eq!(
            effective_permission("shell", &overrides),
            PermissionState::AskEachTime,
            "tier default should be returned when no user override exists"
        );
    }

    #[test]
    fn test_effective_permission_unknown_tool_defaults_to_ask() {
        let overrides = HashMap::new();

        assert_eq!(
            effective_permission("completely_unknown_tool_xyz", &overrides),
            PermissionState::AskEachTime,
            "unknown tool should default to AskEachTime"
        );
    }

    #[test]
    fn test_admin_tool_policy_global_disabled() {
        let policy = AdminToolPolicy {
            disabled_tools: vec!["build_software".to_string(), "tool_install".to_string()],
            ..Default::default()
        };
        assert!(policy.is_tool_disabled("build_software", "any_user"));
        assert!(policy.is_tool_disabled("tool_install", "any_user"));
        assert!(!policy.is_tool_disabled("shell", "any_user"));
    }

    #[test]
    fn test_admin_tool_policy_per_user_disabled() {
        let mut user_tools = HashMap::new();
        user_tools.insert("alice".to_string(), vec!["tool_install".to_string()]);
        let policy = AdminToolPolicy {
            user_disabled_tools: user_tools,
            ..Default::default()
        };
        assert!(policy.is_tool_disabled("tool_install", "alice"));
        assert!(!policy.is_tool_disabled("tool_install", "bob"));
        assert!(!policy.is_tool_disabled("shell", "alice"));
    }

    #[test]
    fn test_admin_tool_policy_combined() {
        let mut user_tools = HashMap::new();
        user_tools.insert("alice".to_string(), vec!["shell".to_string()]);
        let policy = AdminToolPolicy {
            disabled_tools: vec!["build_software".to_string()],
            user_disabled_tools: user_tools,
        };
        assert!(policy.is_tool_disabled("build_software", "alice"));
        assert!(policy.is_tool_disabled("build_software", "bob"));
        assert!(policy.is_tool_disabled("shell", "alice"));
        assert!(!policy.is_tool_disabled("shell", "bob"));
    }

    #[test]
    fn test_admin_tool_policy_empty() {
        let policy = AdminToolPolicy::default();
        assert!(policy.is_empty());
        assert!(!policy.is_tool_disabled("anything", "anyone"));
    }

    #[test]
    fn test_admin_tool_policy_serde_roundtrip() {
        let mut user_tools = HashMap::new();
        user_tools.insert("alice".to_string(), vec!["shell".to_string()]);
        let policy = AdminToolPolicy {
            disabled_tools: vec!["build_software".to_string()],
            user_disabled_tools: user_tools,
        };
        let json = serde_json::to_value(&policy).expect("serialize");
        let restored: AdminToolPolicy = serde_json::from_value(json).expect("deserialize");
        assert_eq!(policy, restored);
    }

    #[test]
    fn test_admin_tool_policy_deserialize_partial() {
        let json = serde_json::json!({"disabled_tools": ["build_software"]});
        let policy: AdminToolPolicy = serde_json::from_value(json).expect("deserialize");
        assert_eq!(policy.disabled_tools, vec!["build_software"]);
        assert!(policy.user_disabled_tools.is_empty());
    }

    #[test]
    fn test_settings_serde_roundtrip() {
        let mut settings = Settings::default();
        settings
            .tool_permissions
            .insert("shell".to_string(), PermissionState::AlwaysAllow);
        settings
            .tool_permissions
            .insert("restart".to_string(), PermissionState::Disabled);

        // Round-trip through JSON (the primary serialization format).
        let json = serde_json::to_string(&settings).expect("serialize");
        let loaded: Settings = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(
            loaded.tool_permissions.get("shell"),
            Some(&PermissionState::AlwaysAllow)
        );
        assert_eq!(
            loaded.tool_permissions.get("restart"),
            Some(&PermissionState::Disabled)
        );
        // Tool not in the map should be absent (not defaulted to anything).
        assert!(!loaded.tool_permissions.contains_key("echo"));
    }
}
